# Generated by Django 4.2.16 on 2026-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='cart',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='pending_order',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='selected_subcategory',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
