# Generated by Django 4.2.16 on 2026-05-06 07:10

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=orders.models.generate_order_code, max_length=20, unique=True)),
                ('source', models.CharField(choices=[('web', 'Sayt'), ('bot', 'Telegram bot')], default='web', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('shipped', "Yo'lda"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20)),
                ('customer_first_name', models.CharField(max_length=120)),
                ('customer_last_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(max_length=40)),
                ('customer_city', models.CharField(blank=True, max_length=120)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('customer_note', models.TextField(blank=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=120)),
                ('delivery_method', models.CharField(choices=[('standard', 'Standart'), ('express', 'Tezkor'), ('pickup', "Do'kondan olib ketish")], default='standard', max_length=20)),
                ('delivery_cost', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('card', 'Karta'), ('click', 'Click/Payme'), ('cash', 'Naqd')], default='card', max_length=20)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_brand', models.CharField(blank=True, max_length=120)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
