# Generated by Django 4.2.16 on 2026-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_order_user_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd')], default='card', max_length=20),
        ),
    ]
